apiVersion: apps/v1
kind: Deployment
metadata:   
   name: demoapp
   labels:   
      app: demoapp
spec:   
   selector:   
      matchLabels:   
         app: demoapp
   template:   
      metadata:   
         labels:   
            app: demoapp
         annotations:   
            prometheus.io/scrape: "true"
            prometheus.io/port: "8082"
            prometheus.io/path: "/actuator/prometheus"
      spec:   
         containers:   
            - name: demoapp
              image: demoapp:v2
              imagePullPolicy: Never
              ports:
                 - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:    
   name: demoapp
   labels:   
      app: demoapp
spec:   
   ports:
      - protocol: TCP
        name: http-traffic
        port: 8082
        targetPort: 8082
   selector:
     app: demoapp               