---
   networks:
      test: 
         
   services:
      monitoringapp:
         image:   demoapp:v1
         networks:   
            - test   
         ports:
            - "8082:8082"
      prometheus:
         image: prom/prometheus
         networks:   
            - test         
         volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
         ports:
            - "9090:9090"